# Generated by Django 5.1.3 on 2024-12-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('youtube_url', models.URLField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('episodes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.CharField(blank=True, max_length=50, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('background', models.TextField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
